/*     */ package com.zaxxer.hikari.pool;
/*     */ 
/*     */ import java.sql.Connection;
/*     */ import java.sql.ResultSet;
/*     */ import java.sql.SQLException;
/*     */ import java.sql.Statement;
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ public abstract class ProxyStatement
/*     */   implements Statement
/*     */ {
/*     */   protected final ProxyConnection connection;
/*     */   final Statement delegate;
/*     */   private boolean isClosed;
/*     */   private ResultSet proxyResultSet;
/*     */   
/*     */   ProxyStatement(ProxyConnection connection, Statement statement) {
/*  39 */     this.connection = connection;
/*  40 */     this.delegate = statement;
/*     */   }
/*     */ 
/*     */   
/*     */   final SQLException checkException(SQLException e) {
/*  45 */     return this.connection.checkException(e);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public final String toString() {
/*  52 */     String delegateToString = this.delegate.toString();
/*  53 */     return getClass().getSimpleName() + '@' + System.identityHashCode(this) + " wrapping " + delegateToString;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public final void close() throws SQLException {
/*  64 */     synchronized (this) {
/*  65 */       if (this.isClosed) {
/*     */         return;
/*     */       }
/*     */       
/*  69 */       this.isClosed = true;
/*     */     } 
/*     */     
/*  72 */     this.connection.untrackStatement(this.delegate);
/*     */     
/*     */     try {
/*  75 */       this.delegate.close();
/*     */     }
/*  77 */     catch (SQLException e) {
/*  78 */       throw this.connection.checkException(e);
/*     */     } 
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public Connection getConnection() throws SQLException {
/*  86 */     return this.connection;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean execute(String sql) throws SQLException {
/*  93 */     this.connection.markCommitStateDirty();
/*  94 */     return this.delegate.execute(sql);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
/* 101 */     this.connection.markCommitStateDirty();
/* 102 */     return this.delegate.execute(sql, autoGeneratedKeys);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public ResultSet executeQuery(String sql) throws SQLException {
/* 109 */     this.connection.markCommitStateDirty();
/* 110 */     ResultSet resultSet = this.delegate.executeQuery(sql);
/* 111 */     return ProxyFactory.getProxyResultSet(this.connection, this, resultSet);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int executeUpdate(String sql) throws SQLException {
/* 118 */     this.connection.markCommitStateDirty();
/* 119 */     return this.delegate.executeUpdate(sql);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int[] executeBatch() throws SQLException {
/* 126 */     this.connection.markCommitStateDirty();
/* 127 */     return this.delegate.executeBatch();
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
/* 134 */     this.connection.markCommitStateDirty();
/* 135 */     return this.delegate.executeUpdate(sql, autoGeneratedKeys);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
/* 142 */     this.connection.markCommitStateDirty();
/* 143 */     return this.delegate.executeUpdate(sql, columnIndexes);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public int executeUpdate(String sql, String[] columnNames) throws SQLException {
/* 150 */     this.connection.markCommitStateDirty();
/* 151 */     return this.delegate.executeUpdate(sql, columnNames);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean execute(String sql, int[] columnIndexes) throws SQLException {
/* 158 */     this.connection.markCommitStateDirty();
/* 159 */     return this.delegate.execute(sql, columnIndexes);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public boolean execute(String sql, String[] columnNames) throws SQLException {
/* 166 */     this.connection.markCommitStateDirty();
/* 167 */     return this.delegate.execute(sql, columnNames);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public long[] executeLargeBatch() throws SQLException {
/* 174 */     this.connection.markCommitStateDirty();
/* 175 */     return this.delegate.executeLargeBatch();
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public long executeLargeUpdate(String sql) throws SQLException {
/* 182 */     this.connection.markCommitStateDirty();
/* 183 */     return this.delegate.executeLargeUpdate(sql);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public long executeLargeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
/* 190 */     this.connection.markCommitStateDirty();
/* 191 */     return this.delegate.executeLargeUpdate(sql, autoGeneratedKeys);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public long executeLargeUpdate(String sql, int[] columnIndexes) throws SQLException {
/* 198 */     this.connection.markCommitStateDirty();
/* 199 */     return this.delegate.executeLargeUpdate(sql, columnIndexes);
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public long executeLargeUpdate(String sql, String[] columnNames) throws SQLException {
/* 206 */     this.connection.markCommitStateDirty();
/* 207 */     return this.delegate.executeLargeUpdate(sql, columnNames);
/*     */   }
/*     */ 
/*     */ 
/*     */   
/*     */   public ResultSet getResultSet() throws SQLException {
/* 213 */     ResultSet resultSet = this.delegate.getResultSet();
/* 214 */     if (resultSet != null) {
/* 215 */       if (this.proxyResultSet == null || ((ProxyResultSet)this.proxyResultSet).delegate != resultSet) {
/* 216 */         this.proxyResultSet = ProxyFactory.getProxyResultSet(this.connection, this, resultSet);
/*     */       }
/*     */     } else {
/*     */       
/* 220 */       this.proxyResultSet = null;
/*     */     } 
/* 222 */     return this.proxyResultSet;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public ResultSet getGeneratedKeys() throws SQLException {
/* 229 */     ResultSet resultSet = this.delegate.getGeneratedKeys();
/* 230 */     if (this.proxyResultSet == null || ((ProxyResultSet)this.proxyResultSet).delegate != resultSet) {
/* 231 */       this.proxyResultSet = ProxyFactory.getProxyResultSet(this.connection, this, resultSet);
/*     */     }
/* 233 */     return this.proxyResultSet;
/*     */   }
/*     */ 
/*     */ 
/*     */ 
/*     */ 
/*     */   
/*     */   public final <T> T unwrap(Class<T> iface) throws SQLException {
/* 241 */     if (iface.isInstance(this.delegate)) {
/* 242 */       return (T)this.delegate;
/*     */     }
/* 244 */     if (this.delegate != null) {
/* 245 */       return this.delegate.unwrap(iface);
/*     */     }
/*     */     
/* 248 */     throw new SQLException("Wrapped statement is not an instance of " + iface);
/*     */   }
/*     */ }


/* Location:              G:\git\codeReviewLog\nginxWebUi\nginxWebUI-3.4.6.jar!\com\zaxxer\hikari\pool\ProxyStatement.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */